### ISSUE TITLE
Can't install google gems

### ISSUE THREAD

**Issue by BritneyMuller** [mtempel/spreadsheetDemo#1]
Keep getting this terminal response:
Unknown command google_drive

TO:

gem 'google_drive'

OR

gem 'google-spreadsheet-ruby'

**Comment by BritneyMuller** [comment]
Fixed it!

$ sudo gem install google_drive

**Comment by BritneyMuller** [comment]
Nevermind...still having problems with this...

**Comment by JacobEvelyn** [comment]
@BritneyMuller you probably want to use bundler, i.e. put those two lines in your `Gemfile` and then run `bundle install` (you may have to `gem install bundler` first). A more straightforward way is to just run `gem install google_drive` and `gem install google-spreadsheet-ruby` in your terminal.

Hope that helps!
